### ISSUE TITLE
Can we set the initial date to be empty?

### ISSUE THREAD

**Issue by wwqq03** [arqex/react-datetime#14]
Hi,

Now I am using this component in a form, and the date field is not mandetory. So I think it should be able to initialize the input as empty, so it won't confuse the users.
And when we delete the date in the input, it won't call the "onChange" callback. I think it should, because users want to delete the date field when this component is in a form.

**Comment by arqex** [comment]
Oh, never thought about that way of using the datepicker. I will have a look at how can I implement the empty date scenario, and I will do it soon.

Thanks for the suggestion.

**Comment by wwqq03** [comment]
Thanks :)

**Comment by tcgardner** [comment]
As a tangent to the empty date, a placeholder prop could be helpful.  I have a case where I do not want to default to a date, but placeholder instructions.

**Comment by arqex** [comment]
@tcgardner you can use the prop `inputProps` to add the placehoder attribute to the input once the picker accepts an empty value.

**Comment by arqex** [comment]
Hey guys,

With the new version, the date field can be empty. Basically, whenever the input gets modified and its value is not a valid date value, `onChange` and `onBlur` return the input value instead of a moment object.

http://codepen.io/arqex/pen/jPjmpQ

Be careful, because moment parse some strings as valid that for me have no sense, but it is a moment issue.
