### ISSUE TITLE
I can't see in the documentation how you actually get the value

### ISSUE THREAD

**Issue by EwanValentine** [arqex/react-datetime#19]
I can't actually see in the readme where you get the value of `<Datepicker />`? Can you still use `refs`?

**Comment by EwanValentine** [comment]
Ignore this, I was being stupid.

**Comment by Sparragus** [comment]
How did you end up doing it? I know `onChange` will let you get the value but I would like to do it using `refs`.

**Comment by GuiRitter** [comment]
Still no docs. I must be stupid too...

**Comment by arqex** [comment]
Hey!

I think this is an usual problem for developers starting using react, don't know if this is your case.

Input type of components are usually used in a controlled way, so weset the prop `value` with some date that westore and keep track of it.

Then when the value changes, weneed to update the value of our variable, and that will be given again to the datepicker. So wealways have the value stored by ourselves.

See react docs: https://reactjs.org/docs/forms.html#controlled-components

In case you don't like controlled components (that you should if you are using react) you can use it in a uncontrolled way using `defaultValue` and you can listen to changes using `onChange`. The problem is that you won't be able to update the value programmatically that way. You are just a listener.

https://reactjs.org/docs/uncontrolled-components.html

In case you don't like any of those alternatives, you can access to the internal state of the component's instance using refs. Totally discouraged, because internals can change at any time without any advice breaking your application completely. If we don't care about it and want to use the component in a way it was never thought of, it's possible to access to the internal value using:

```
// in the render method
<Datetime ref={ instance => this.picker = instance  }/>

// anywhere else in the component
let date = this.picker.state.selectedValue
```

**Comment by jai1331** [comment]
@arqex It's a nice plug in but It would be better if you put how to get Datetime component value when onChange and how to set initial value
