### ISSUE TITLE
isValidDate called too much times

### ISSUE THREAD

**Issue by c0dester** [arqex/react-datetime#622]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Pass some function as isValidDate prop to react-datetime. Put console.log in there

### Expected Results
There is no call of isValidDate before opening calendar dropdown

### Actual Results
isValidDate called too much times before opening calendar dropdown, and after that

isValidDate is called around 80 times before I open calendar dropdown. IMO it shouldn't do that at all, because user doesn't need to have validated dates before he/she sees calendar. When I open calendar by clicking date input, isValidDate is called second time, about 40 times. I'm not familiar with code, but I think, isValidDate should be called only for all days in month (up to 31) and next set of invocations should be after changing month. We have almost 130 invocations in total.
![zrzut ekranu 2019-02-22 o 11 20 25](https://user-images.githubusercontent.com/30890587/53236934-bff45a80-3695-11e9-836b-577950382be2.png)

**Comment by arqex** [comment]
Hi c0dester,

Thanks for your feedback. `isValid` is called once for every day printed in order to set specific styles for days that are not valid, and then they are not clickable.

The calendar view is rendered even when the calendar is closed, that allows people to animate how the calendar is shown/hidden using CSS, that's why is valid is called even before the calendar is open.

What we can do is stopping re-rendering the whole calendar actively if it's not going to be updated using `componentShouldUpdate`. Something to work on, but I think it's not near in the library roadmap.

I'll leave the ticket open in order to tackle it in the future.

**Comment by ne0guille** [comment]
hey @arqex is there any way to select a range of years to render?

**Comment by arqex** [comment]
@ne0guille You can now customize the years view completely by using the `renderView` prop.

We are moving towards not rendering the calendar when it's closed, so I'll close this ticket and this issue will be tackled along with https://github.com/arqex/react-datetime/issues/648
