### ISSUE TITLE
onChange does not fire when focus is locked

### ISSUE THREAD

**Issue by 2Shaun** [arqex/react-datetime#710]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Return a date time picker.
2. Return another component.
3. Force focus on the other component.
4. Try to change date on `Datetime` picker calendar.

### Expected Results

onChange fires

### Actual Results

onChange does not fire

### Minimal Reproduction of the Problem

```javascript
import Datetime from 'react-datetime';
import FocusTrap from 'focus-trap-react';

<Datetime open />
<FocusTrap>
    <div>
        <input type="text" />
    </div>
</FocusTrap>
```
I couldn't figure out how to import [focus-trap-react](https://www.npmjs.com/package/focus-trap-react) into codepen.
### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
This is not an issue for the timepicker. If you do
```javascript
<Datetime open dateFormat={false} />
<FocusTrap>
    <div>
        <input type="text" />
    </div>
</FocusTrap>
```
the `Datetime` picker will work as intended.

**Comment by jmburdette** [comment]
it's true that `onChange` will fire if you set the dateFormat to false but now when the calendar opens you can't choose the date.

@2Shaun have you found a work around?

**Comment by 2Shaun** [comment]
I wanted to use blur/unfocus of the text box to close the calendar. My workaround was to set `onBlur` to `() => {}` while hovering over the calendar (wrapped in a `<div>`).

**Comment by arqex** [comment]
Here it is:

https://codesandbox.io/s/determined-wiles-hzo6z?file=/src/App.js

I don't get the issue. If the datepicker is out of the focus trap, why should it be updated? A focus trap is used to make the rest of the app not to be actionable, doesn't it?

**Comment by 2Shaun** [comment]
Thank you for working that out, @arqex .

Here's the example of the time picker that functions while the textbox is focus trapped:
https://codesandbox.io/s/snowy-shadow-j7icd?file=/src/App.js

I hope you're not calling _that_ a bug! I can imagine making something unfocusable but still able to click on it. I can also imagine events, such as hover, that the app must listen for while not being focused. I'm not sure what you mean by "actionable" here, though.

**Comment by arqex** [comment]
What I meant with actionable is that focus traps are intended to be used with modals or pop-ups, so the content behind the modal is not accessible to the user through the keyboard or the mouse.

The trap hijacks clicks and tabs to keep the interaction into the modal, and it actually deactivates all the rest.

I've added a google link to your example that can't be clicked either, because it is out of the trap:

https://codesandbox.io/s/strange-mountain-bb128?file=/src/App.js

So the calendar not responding out of the trap would be the correct behavior. 

The time picker is responding because is not using `click` events, but `mousedown` and `mouseup` ones. In that case `focus-trap-react` is failing to hijack that interaction. But the timepicker working out of the trap is not a problem of react-datetime, it's a focus-trap-react's problem.
